server:
  port: 8080
  servlet:
    context-path: /laptopshop/v0.1

spring:
  application:
    name: back-end

  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: minhthong262003@gmail.com
    password: ttgs aafn pltm yyco
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 964732288594-4gqoggefb34c97skb951vc4hnnkptk7j.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          facebook:
            client-id: 1562454040935985
            client-secret: 50d9c75f03a9c5130e6517ef38c976a4
            scope: email, public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"

file:
  upload-dir: uploads/

SIGNER_KEY: Ls0Xqw3hOsUSFeHJ6QQNFtsFXmbcIpCay4gqTORtO89WHZyOYgdnSs0aiQKe2otd

paypal:
  client-id: ARpim4ec-DFFNBFDn8AOzHYR-KN4_sjy8L5k3knSpZKyArMZoIsWbden9iTai_3lMY4wlY4BVxB5UnVT
  client-secret: ED5EK0yGyZLgCNtMnhRujsg5ESCmd3Rv2krMmVILlWRh3FLw_sZnGMJOyUXHXlLfAZUNsojRVkf0u0iY
  mode: sandbox


log:
  formatDate: yyyy-MM-dd
  path: ./home
  file:
    name: service_log
    ext: .log
    maxMb: 1
    maxHistory: 10
    zip:
      ext: .zip
      pattern: service_log_%d{yyyy-MM-dd}.%i.zip
